export default {
  CLASSNAME: {
    DONUT_WRAPPER: '',
    DONUT_ITEM: '',
    DONUT_LEFT: '',
    DONUT_RIGHT: '',
    DONUT_LEFT_BOX: '',
    DONUT_RIGHT_BOX: '',
    DONUT_INNER_CIRCLE: '',
    ITEM_CONTENTS_WRAP: '',
    ITEM_CONTENTS_POINT: '',
    ITEM_CONTENTS_GUIDELINE: '',
    ITEM_CONTENTS: '',
  },
  STYLESHEET: {
    DONUT_WRAPPER: {
      overflow: 'hidden',
      position: 'relative',
      width: '500px',
      height: '500px',
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      'background-color': '#ffffff',
      'border': '1px solid rgba(0,0,0,0.5)',
      'box-shadow': '5px 5px 5px rgba(0,0,0,0.15)',
    },
    DONUT_ITEM: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      'background-color': 'eee',
    },
    DONUT_LEFT: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '50%',
      height: '100%',
    },
    DONUT_RIGHT: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      right: 0,
      width: '50%',
      height: '100%',
    },
    DONUT_LEFT_BOX: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      '-webkit-transform-origin': '100% 50%',
      'transform-origin': '100% 50%',
      '-webkit-transform': 'rotate(180deg)',
      transform: 'rotate(180deg)',
    },
    DONUT_RIGHT_BOX: {
      position: 'absolute',
      top: 0,
      left: '-100%',
      width: '100%',
      height: '100%',
      '-webkit-transform-origin': '100% 50%',
      'transform-origin': '100% 50%',
      '-webkit-transform': 'rotate(0deg)',
      transform: 'rotate(0deg)',
    },
    DONUT_INNER_CIRCLE: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      'z-index': 2,
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      'background-color': '#ffffff',
      'border': '1px solid rgba(0,0,0,0.5)',
    },
    ITEM_CONTENTS_WRAP: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      '-webkit-transform': 'rotate(0deg)',
      transform: 'rotate(0deg)',
    },
    ITEM_CONTENTS_POINT: {
      position: 'absolute',
      top: 0,
      left: '50%',
      width: 0,
      height: 0,
    },
    ITEM_CONTENTS_GUIDELINE: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      '-webkit-transform-origin': '0 0',
      'transform-origin': '0 0',
      '-webkit-transform': 'rotate(0deg) translateX(-50%) translateY(-50%)',
      transform: 'rotate(0deg) translateX(-50%) translateY(-50%)',
      'text-align': 'center',
    },
    ITEM_CONTENTS: {
      display: 'inline-block',
      'vertical-align': 'top',
      'word-wrap': 'break-word',
      'word-break': 'break-all',
    },
  },
};
