export default {
  CLASSNAME: {
    DONUT: '__donut',
    DONUT_ITEM: '__item',
    DONUT_LEFT: '__left',
    DONUT_RIGHT: '__right',
    DONUT_LEFT_BOX: '__left_box',
    DONUT_RIGHT_BOX: '__right_box',
    DONUT_INNER_CIRCLE: '__inner_circle',
    DONUT_CONTENTS_POINT: '__contents_point',
    DONUT_CONTENTS_GUIDELINE: '__contents_guideline',
    DONUT_CONTENTS_HTML: '__contents_html',
  },
  STYLESHEET: {
    DONUT: {
      position: 'relative',
      width: '500px',
      height: '500px',
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      '-webkit-box-sizing': 'border-box',
      'box-sizing': 'border-box',
    },
    DONUT_ITEM: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      'background-color': 'eee',
    },
    DONUT_LEFT: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      left: 0,
      width: '50%',
      height: '100%',
    },
    DONUT_RIGHT: {
      overflow: 'hidden',
      position: 'absolute',
      top: 0,
      right: 0,
      width: '50%',
      height: '100%',
    },
    DONUT_LEFT_BOX: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      '-webkit-transform-origin': '100% 50%',
      'transform-origin': '100% 50%',
      '-webkit-transform': 'rotate(180deg)',
      transform: 'rotate(180deg)',
    },
    DONUT_RIGHT_BOX: {
      position: 'absolute',
      top: 0,
      left: '-100%',
      width: '100%',
      height: '100%',
      '-webkit-transform-origin': '100% 50%',
      'transform-origin': '100% 50%',
      '-webkit-transform': 'rotate(0deg)',
      transform: 'rotate(0deg)',
    },
    DONUT_INNER_CIRCLE: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      'z-index': 2,
      '-webkit-border-radius': '50%',
      'border-radius': '50%',
      '-webkit-box-sizing': 'border-box',
      'box-sizing': 'border-box',
    },
    DONUT_CONTENTS_POINT: {
      position: 'absolute',
      top: 0,
      left: 0,
      width: 0,
      height: 0,
      'z-index': 3,
    },
    DONUT_CONTENTS_GUIDELINE: {
      position: 'absolute',
      top: '50%',
      left: '50%',
      '-webkit-transform': 'translateY(-50%)',
      transform: 'translateY(-50%)',
      'text-align': 'center',
    },
    DONUT_CONTENTS_HTML: {
      display: 'inline-block',
      'vertical-align': 'top',
      'word-wrap': 'break-word',
      'word-break': 'break-all',
    },
  },
};
